# -*- coding: utf-8 -*-
"""Text_vecotrization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-tQ8uHxVdHGxkRhf5LLK3WJtOn9sVzvv
"""

import pandas as pd
import numpy as np
import tensorflow as tf
import string
import re
from tensorflow.keras.layers import TextVectorization

dataset = ["I write, erase, rewrite",
           "Erase again and then",
           "A poppy blooms."]

text_vector = TextVectorization(
)

text_vector.adapt(dataset)

text_vector.get_vocabulary()

vocab = text_vector.get_vocabulary()
test_sentence = "I write, rewrite and still rewrite again and poppy"
encode_sentence = text_vector(test_sentence)
print(encode_sentence)

inverse_vocab = dict(enumerate(vocab))
decoded_sentence = " ".join(inverse_vocab[int(i)] for i in encode_sentence)
print(decoded_sentence)